<a href="https://colab.research.google.com/github/Aswathyvsajeev/Datascience-libraries/blob/main/DataScience_NumPy_library_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

In [2]:
import numpy as np
import time
import sys
#a is a two dimensional array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


One advantage of numpy array over list is that it occupies less space compared to list

In [ ]:
#list
s = range(1000)
print(sys.getsizeof(5)*len(s))
#numpy array
d= np.arange(1000)
print(d.size * d.itemsize)

28000
8000


In [ ]:
# List to numpy array
my_list = [1,2,3]
arr = np.array(my_list)
#This is a one dimensional array
arr

array([1, 2, 3])

In [ ]:
# Two -dimensional array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
test = np.array(my_mat)
print(test)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(test.data)
print(test.shape)


In [6]:
#arange function to generate numpy array
np.arange(0,10)
#only passing value for mandatory parameter
np.arange(9)
#with step parameter
np.arange(1,10,2)
#with data type parameter
np.arange(1,10,dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [11]:
np.zeros(5)
# Default data type is float .we can change it also.
np.zeros(5,dtype = "int")
# we can create two dimensional array using tuple or list
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#ones() function to create array of ones
np.ones(8,dtype = "int")
#multi-dimensional array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#linspace function to create numpy array
np.linspace(1,5,10)
np.linspace(2,5,num = 5,retstep=True)
np.linspace(1,100,endpoint=False,num =5,dtype="int")

array([ 1, 20, 40, 60, 80])

In [3]:
#eye function to generate numpy array filled with zeros except in the k-th diagonal,whose value equal to 1.
np.eye(3)
np.eye(4, k =-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
help(np.random)

In [6]:
np.random.rand(3,2)

array([[0.83467723, 0.07167791],
       [0.26336046, 0.61495361],
       [0.65634262, 0.8621567 ]])

In [8]:
np.random.randint(5,size = (2,4))

array([[4, 4, 0, 3],
       [0, 2, 3, 0]])

In [14]:
# Attributes of numpy array
a =  np.array([[3,2,1,5],[3,4,5,7]])
print(a.ndim)
print(a)

2
[[3 2 1 5]
 [3 4 5 7]]


In [31]:
d = np.zeros((2,3,4),dtype = "int")
print(b)
print(b.size)
print(b.dtype)
print(d.itemsize)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
24
float64
8


In [33]:
e = np.array([[2,3],[4,5]])
print(e.dtype)
print(e.itemsize)

int64
8


In [4]:
#datatype in numpy library
x = np.float32(1)
x.dtype


dtype('float32')

In [11]:
#indexing in numpy array 
#one dimensional array indexing
y = np.array([2,3,4])
print(y[-1])
z = np.array([[4,5,6],[1,2,3]])
print(z)
print(z[-1][2])


4
[[4 5 6]
 [1 2 3]]
3
[2 3]
